<?php
$helper = Mage::helper('pdp');
$fonts = $helper->getFonts();
?>
<!DOCTYPE html>
<html>
	<head>
		<script type='text/javascript' src='<?php echo $this->getJsUrl('pdp/js/jquery-latest.js') ?>'></script>
		<script type='text/javascript' src='<?php echo $this->getJsUrl('pdp/js/viewfinaldesign.js') ?>'></script>
		<title><?php echo $this->__('Final Design Review'); ?></title>
		<style type="text/css">
			<?php foreach ( $fonts as $font) { ?>
			@font-face {
				font-family: '<?php echo $font->getName() ?>';
				src: url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>pdp/fonts/<?php echo $font->getName() ?>.<?php echo $font->getExt() ?>');
			}
			<?php } ?>
			#print_btn {
				background: url('<?php echo $this->getJsUrl('pdp/images/printer.png') ?>') no-repeat scroll center center / 50px auto rgba(0, 0, 0, 0);
				cursor: pointer;
			    min-height: 50px;
			    min-width: 50px;
			    position: absolute;			
			}
			@media print{
				#wrapper #design_result .img_result {
					margin-left: 90px !important;
				}
			}
		</style>
	</head>
	<body>
		<div id='wrapper'>
			<span id='print_btn' onclick="window.print()"></span>
			<div id='final_design'>
			<?php 
				$orderNumber = Mage::app()->getRequest()->getParam('id');
                $did = Mage::app()->getRequest()->getParam('did');
				if (($orderNumber != "")&&($did != "")) {
					$order = Mage::getModel('sales/order')->loadByIncrementId($orderNumber);
					$orderItems = $order->getItemsCollection(); 
					if ( count($orderItems) ) {
						foreach ($orderItems as $item){
							$seriaOption = unserialize($item->getData('product_options'));
                            $design_id = $item->getData('item_id');
                            if($design_id==$did){
    							$itemOptions = $seriaOption['options'];
    							foreach ($itemOptions as $_option) {
    								if ($_option['label'] == "pdpinfo") {
    									echo "<input id='design_option_".$design_id."' type='hidden' value='" . $_option['value'] . "' name='option[]' class='design-option' />";
    								}
    							}
                            }
						}
					}
				} else {
					echo "<h3>Found no order id</h3>";
				}
			?>
			</div>
			<div id="design_result" style="float: left;"></div>
		</div>
	</body>
</html>
